import type { Metadata } from "next";
import "./globals.css";
import { Saira } from 'next/font/google'
import { Header } from "@/components/header";

const saira = Saira({
  subsets: ['latin'],
  weight: ['300','400','500','600']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${saira} antialiased`}
      >
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
